<div class="panel-heading">                    		        	
  <h3 class="head-border" translate="<?php echo 'NAV_SUB_'.strtoupper($subMenuActive)?>"><?php echo $subMenuActive ?></h3>
</div>
<div class="panel-body panel-team"> 
  <div class="last-info">                    
    <div class="news-image">
      <a href="<?php echo $app->basePath('public/img/teams/mlodziki.jpg'); ?>" data-lightbox="image-1" title="{{ <?php echo 'NAV_SUB_'.strtoupper($subMenuActive)?> | translate}}">
        <img src="<?php echo $app->basePath('public/img/teams/mlodziki.jpg'); ?>" alt="{{ <?php echo 'NAV_SUB_'.strtoupper($subMenuActive)?> | translate}}" title="{{ <?php echo 'NAV_SUB_'.strtoupper($subMenuActive)?> | translate}}" class="img-responsive">
      </a>
    </div>
  </div>  
  <div class="alert alert-warning" translate="SOON_LIST_OF_PLAYERS">Wkrótce lista zawodników</div>
</div>
