<section class="breadcrumbs">
  <div class="container">    
    <ul class="breadcrumb">
      <li><a href="<?php echo $app->basePath('') ?>"><i class="fa fa-home"></i></a></li>
      <?php if(isset($overRideMenu)) : ?>
        <li><a href="<?php echo $app->basePath($overRideMenu) ?>" translate="<?php echo "NAV_".strtoupper($overRideMenu) ?>"><?php echo 'NAV_'.strtoupper($overRideMenu) ?></a></li>
      <?php else : ?>    
        <li><a href="<?php echo $app->basePath($menuActive) ?>" translate="<?php echo "NAV_".strtoupper($menuActive) ?>"><?php echo 'NAV_'.strtoupper($menuActive) ?></a></li>
      <?php endif; ?>
      
      <?php if($subMenuActive != '') : ?>
        <li translate="NAV_SUB_<?php echo strtoupper($subMenuActive) ?>"><?php echo 'NAV_SUB_'.strtoupper($subMenuActive) ?></li>      
      <?php endif; ?>    
      <?php if(isset($singleItemNews)) : ?>
        <li class="item-overflow"><?php echo $singleItemNews; ?></li>      
      <?php endif; ?>
    </ul>
  </div>        
</section>