<head lang="pl">
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $title ?></title>            
  <meta name="description" content="Dragons United Polish Football Academy - Zaprasza na treningi piłkarskie chłopców i dziewczynki od 3 do 16 lat." />
  <meta name="keywords" content="dragonsunited, dragons, Dragons United, Polish Football Academy, England football, Akademia Piłkarska, WEMBLEY, Treningi piłkarskie" />                
  <meta name="title" content="Dragons United Polish Football Academy - Zaprasza na treningi piłkarskie chłopców i dziewczynki od 3 do 16 lat.">
  
  <meta name="msvalidate.01" content="4918BD95B6C6CA78EF52B02F779745F5" />
  <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $app->basePath('public/favicon/apple-icon-57x57.png'); ?>">
  <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $app->basePath('public/favicon/apple-icon-60x60.png'); ?>">
  <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $app->basePath('public/favicon/apple-icon-72x72.png'); ?>">
  <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $app->basePath('public/favicon/apple-icon-76x76.png'); ?>">
  <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $app->basePath('public/favicon/apple-icon-114x114.png'); ?>">
  <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $app->basePath('public/favicon/apple-icon-120x120.png'); ?>">
  <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $app->basePath('public/favicon/apple-icon-144x144.png'); ?>">
  <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $app->basePath('public/favicon/apple-icon-152x152.png'); ?>">
  <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $app->basePath('public/favicon/apple-icon-180x180.png'); ?>">
  <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $app->basePath('public/favicon/android-icon-192x192.png'); ?>">
  <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $app->basePath('public/favicon/favicon-32x32.png'); ?>">
  <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $app->basePath('public/favicon/favicon-96x96.png'); ?>">
  <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $app->basePath('public/favicon/favicon-16x16.png?v=22'); ?>">
  <link rel="icon" href="<?php echo $app->basePath('public/favicon/favicon.ico?v=22'); ?>" type="image/x-icon">   
  <link rel="shortcut icon" href="<?php echo $app->basePath('public/favicon/favicon.ico?v=22'); ?>" type="image/x-icon">                             
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="robots" content="index, follow">
  <link href='http://fonts.googleapis.com/css?family=Kaushan+Script&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="<?php echo $app->basePath('public/css/bootstrap/css/bootstrap.min.css'); ?>">    
  <link rel="stylesheet" href="<?php echo $app->basePath('public/vendor/fontawesome/css/font-awesome.min.css'); ?>">    
    
  <link rel="stylesheet" href="<?php echo $app->basePath('public/css/screen.css?v=2015-06'); ?>">    
  <!-- angular -->
  <script src="<?php echo $app->basePath('public/js/angular/angular.min.js?v=2015') ?>" ></script>
  <script src="<?php echo $app->basePath('public/js/angular/angular-translate.min.js?v=2015') ?>" ></script>  
  <script src="<?php echo $app->basePath('public/js/angular/angular-ext-new.js?v=2015-6') ?>" ></script>
</head>