<?php if ($news) : ?>
<?php foreach ($news as $i) : ?>
  <div class="information">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">   
        <div class="img-information text-center">
          <?php if ($i['news_image']) : ?>
            <img src="<?php echo $app->basePath('admin/img/news/small_' . $i['news_image']) ?>" alt="img" class="img-responsive"/>
          <?php else: ?>
            <img src="<?php echo $app->basePath('public/img/default_news.jpg') ?>" alt="img" class="img-responsive"/>
          <?php endif; ?>
            <div class="overlay"><a href="<?php echo $app->basePath(helpers::link($i['category_name'], $i['news_id'])); ?>"><i class="fa fa-share"></i></a></div>                                
        </div>
      </div>
      <div class="col-md-9 col-sm-6 col-xs-12">
        <h4 class="title">
          <a href="<?php echo $app->basePath(helpers::link($i['category_name'], $i['news_id'])); ?>">
            <?php echo htmlspecialchars($i['news_title']) ?>
          </a>
        </h4>
        <a href="<?php echo $app->basePath(helpers::linkCategory($i['category_name'], $i['news_subcategory'])) ?>" class="category-link">
          <span class="label label-primary" translate="NAV_SUB_<?php echo strtoupper($i['news_subcategory']); ?>"><?php echo $i['news_subcategory']; ?></span>
        </a>
        
        <p class="date"><?php echo date('d.m.Y G:i', ($i['news_insert'])) ?></p>
        <p class="desc"><?php echo helpers::clearHtml($i['news_desc']) ?></p>				
        <a href="<?php echo $app->basePath(helpers::link($i['category_name'], $i['news_id'])); ?>" class="btn btn-default btn-sm"><b translate="TEXT_NEWS_READ">Czytaj </b><i class="fa fa-angle-double-right"></i></a>
      </div>
    </div>
  </div>
<?php endforeach; ?>
<?php else: ?>
  <div class="alert alert-warning" translate="TEXT_NO_ARTILES_IN_ZONE">
    Brak artykułów.
  </div>

<?php endif; ?>



