<div class="sidebar">
  <div class="box">
    <h2 class="title">Reklamy</h2>				
    <div class="adsense">
      <script type="text/javascript">
        google_ad_client = "ca-pub-2109333129587576";
        /* new.malytramwaj */
        google_ad_slot = "1641383897";
        google_ad_width = 300;
        google_ad_height = 250;
      </script>
      <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>                
    </div>                
    <p><small>Chcesz dodać reklamę? Zadzwoń do nas :)</small></p>
    <div class="clear"></div>
  </div>
  <div class="box">
    <h2 class="title">Wyniki meczów</h2>            
    <div class="scores">
      <div>
        <h3>Trampkarze</h3>
        <?php $scoreT = helpers::score('t') ?>    

        <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
        <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
        <p class="tabela"><a href="table.php?c=trampkarze"><span>terminarz i wyniki</span></a></p>
      </div>
      <div>
        <h4>Młodzicy</h4>
        <?php $scoreT = helpers::score('m'); ?>    

        <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
        <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
        <p class="tabela"><a href="table.php?c=mlodzicy"><span>terminarz i wyniki</span></a></p>		
      </div>
      <div>
        <h3>Orliki</h3>
        <?php $scoreT = helpers::score('o'); ?>    

        <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
        <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
        <p class="tabela"><a href="table.php?c=orliki"><span>terminarz i wyniki</span></a></p>
      </div>
      <div>
        <h4>Żaki</h4>                    
        <?php $scoreT = helpers::score('z'); ?>    

        <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
        <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
        <p class="tabela"><a href="table.php?c=zaki"><span>terminarz i wyniki</span></a></p>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>