<section id="newsletter" class="newsletter-container">
  <div class="container">

    <div class="row">
      <div class="col-md-12">

        <h3 class="text-center"><span translate="TEXT_NEWSLETTER_TITLE">Zapisz się do </span><b translate="TEXT_NEWSLETTER_TITLE_BOLD">Newslettera</b></h3>
        <p class="text-center"><span translate="TEXT_NEWSLETTER_DESC">Będziesz otrzymywał wiadomości na bierząco do swojej skrzynki mailowej</span>&ensp;
          <i class="fa fa-info-circle" data-toggle="popover" title="{{'NAV_REGULATIONS'| translate  }}" data-placement="top" data-trigger="focus" tabindex="0" role="button" data-content="{{'TEXT_NEWSLETTER_RULES'| translate  }}"></i>          
        </p>         
        <form class="newsletter-form" id="newsletterForm" data-ng-submit="addPerson(newsletterForm.$valid)" data-ng-controller="newsletterCtrl" name="newsletterForm"  method="post" action="<?php echo $app->basePath('newsletter') ?>" novalidate>
          <div class="alert hidden alert-danger" data-message-ok="{{'TEXT_NEWSLETTER_OK' | translate }}" data-message-remove-ok="{{'TEXT_NEWSLETTER_REMOVED_OK' | translate }}" data-message-err-email="{{'TEXT_WRONG_EMAIL' | translate }}" data-message-err="{{'TEXT_ERROR_OCCURED' | translate }}">

          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6">
              <div class="input-group input-group-lg" ng-class="{'has-error': newsletterForm.newsletterUser.$dirty&&newsletterForm.newsletterUser.$invalid }">
                <span class="input-group-addon" id="sizing-user"><i class="fa fa-user"></i></span>
                <input type="text" class="form-control" placeholder="{{'TEXT_NEWSLETTER_NAME' | translate }}" name="newsletterUser" aria-describedby="sizing-user" required  ng-model="newsletterUser">                
              </div>                        
              <div ng-class="{'has-error': newsletterForm.newsletterUser.$dirty&&newsletterForm.newsletterUser.$invalid }">
                <p class="has-error help-block flipInX" ng-show="newsletterForm.newsletterUser.$dirty && newsletterForm.newsletterUser.$invalid" >{{ 'TEXT_REQUIRED_FIELD' | translate }}</p>
              </div>
            </div>
            <div class="col-md-6 col-sm-6">

              <div class="input-group input-group-lg" ng-class="{'has-error': newsletterForm.newsletterEmail.$dirty&&newsletterForm.newsletterEmail.$invalid }">
                <span class="input-group-addon" id="sizing-email"><i class="fa fa-envelope-o"></i></span>
                <input type="email" class="form-control" placeholder="{{'TEXT_NEWSLETTER_EMAIL' | translate }}" name="newsletterEmail" aria-describedby="sizing-email" required  ng-model="newsletterEmail">
                <span class="input-group-btn">
                  <button class="btn btn-danger" type="submit" translate="TEXT_SAVE_TO_NEWSLETTER" data-loading-text="{{ 'TEXT_CONTACT_SENDING' | translate}}">Zapisz</button>
                </span>                
              </div>
              
              <div ng-class="{'has-error': newsletterForm.newsletterEmail.$dirty&&newsletterForm.newsletterEmail.$invalid }">
                <p class="has-error help-block flipInX" ng-show="newsletterForm.newsletterEmail.$dirty && newsletterForm.newsletterEmail.$invalid" >{{ 'TEXT_WRONG_EMAIL' | translate }}</p>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
