<div id="wrapper">     
  <div class="camera_wrap">
     <?php foreach ($nivoNews as $key=>$i) : ?>         
          <?php if ($i['news_image']) :?>
            <div data-src="<?php echo 'admin/img/news/' . $i['news_image'] ?>">
              <div class="camera_caption">
                <div class="container"> 
                  <div class="row"> 
                    <div class="col-md-9 col-sm-10 col-xs-11">                                    
                      <h2 class="animated flipInX"><a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>"><?php echo $i['news_title'] ?></a></h2>
                      <!--<p class="animated fadeInRight delay1">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                      <div class="more animated fadeInRight delay2"> 
                      <a href="#" class="btn btn-primary" name="subscribe">More Info</a>                                    </div> -->  
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <?php else : ?>
            <div data-<?php echo helpers::nivoImage() ?>>
              <div class="camera_caption">
                <div class="container"> 
                  <div class="row"> 
                    <div class="col-md-9 col-sm-10 col-xs-11">                                    
                      <h2 class="animated flipInX"><a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>"><?php echo $i['news_title'] ?></a></h2>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <?php endif; ?>        
      <?php endforeach; ?>
  </div>
</div>

