<div id="wrapper">
     
  <div class="camera_wrap">
     <?php foreach ($nivoNews as $key=>$i) : ?> 
        <div class="item <?php echo $key==0 ? 'active':''?>">
          <?php if ($i['news_image']) :?>
            <div data-src="<?php echo 'admin/img/news/' . $i['news_image'] ?>"></div>
          <?php else : ?>
            <div data-<?php echo helpers::nivoImage() ?>></div>
          <?php endif; ?>
      <?php endforeach; ?>
  </div>
  
  
    <div id="carousel-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <?php foreach ($nivoNews as $key=>$i) : ?> 
          <li data-target="#carousel-generic" data-slide-to="<?php echo $key ?>" class="<?php echo $key==0 ? 'active':''?>"></li>       
        <?php endforeach; ?>	        
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <?php foreach ($nivoNews as $key=>$i) : ?> 
        <div class="item <?php echo $key==0 ? 'active':''?>">
          <?php if ($i['news_image']) :?>
            <img src="<?php echo 'admin/img/news/' . $i['news_image'] ?>" alt="...">
          <?php else : ?>
            <img <?php echo helpers::nivoImage() ?> alt="...">
          <?php endif; ?>
          
          <div class="carousel-caption">
            <div class="container hidden"> 
                            <div class="row">
                                <div class="col-md-7">
                                    <h1 class="animated fadeInRight">
                                         Dominique Daniels Returns
                                    </h1>   
                                    <p class="animated fadeInRight delay1">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p> 
                                    <div class="more animated fadeInRight delay2">
                                        <a href="#" class="btn btn-primary" name="subscribe">More Info</a>
                                    </div>
                                </div>    
                            </div>                     
                        </div>
            <a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>" class="hidden">
                <div class="message-nivo">
                  <p class="title-nivo"><?php echo htmlspecialchars($i['news_title']) ?></p>
                  <p class="teaser-nivo"> <?php echo helpers::clearHtml($i['news_desc']) ?></p>                      
                  <p class="date-nivo"><?php echo date('d.m.Y G:i', ($i['news_update'])) ?> </p>                      
                </div>
              </a>
          </div>
        </div>
        <?php endforeach; ?>	        
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>

