<section class="owl-container">
  <div class="container">

    <div class="row owl-wrapper">	
      <div class="col-md-12">
        <div id="owl-wrapper-carousel" class="owl-top-carousel invisible fadeInFast">

          <?php foreach ($nivoNews as $key => $i) : ?> 
            
            <div class="thumbnail fadeIn">
              <div class="thumbnail-img-wrap">
                <a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>" class="a-bg-img" 
                   style="background-image: url('<?php echo $i['news_image'] ? 'admin/img/news/'.$i['news_image'] : helpers::nivoSimpleImage() ?>')">                  
                </a>
                <div class="date">                      
                  <span><?php echo date('d/m', ($i['news_update'])) ?></span>
                  <?php echo date('Y', ($i['news_update'])) ?>
                </div>
                <div class="meta-info hidden">
                  <ul>
                    <li><i class="fa fa-user"></i><a href="#">Admin</a></li>                            
                  </ul>
                </div>
              </div>
              <div class="caption">
                <h3><a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>"><?php echo htmlspecialchars($i['news_title']) ?></a></h3>
                <p><?php echo helpers::clearHtml($i['news_desc']) ?></p>               
              </div>
              <a href="<?php echo helpers::link($i['category_name'], $i['news_id']) ?>" class="btn btn-default btn-sm">
                <b translate="TEXT_NEWS_READ" class="ng-scope"></b><i class="fa fa-angle-double-right"></i>
              </a>
            </div>  

          <?php endforeach; ?>				              

        </div>		
      </div>
<?php 
  /*
      <?php $loadLastEvents = $nivo->loadLastEvents(); ?>
      
      <div class="col-md-3 calendar">
        <div class="calendar-wrapper">
          <div class="calendar-title"><h2 translate="TEXT_CALENDAR">Kalendarium</h2></div>
          <div class="wrap-events fadeIn">
            <?php if($loadLastEvents) : ?> 
            <?php foreach ($loadLastEvents as $key => $event) : ?>
              <div class="single-event">                
                <div class="count-down-clock"><i class="fa fa-clock-o"></i>&ensp;<span translate="TEXT_COUNTDOWN">Odliczanie</span></div>
                <div class="calendar-content">
                  <div class="big-counter">
                    <div class="wrap-counter" id="wrap-counter-<?php echo $key; ?>" data-date="<?php echo $app->eventCounter($event['event_date']) ?>"></div>
                    <div class="counter-done hidden" translate="TEXT_DONE_COUNTER">Nieaktualne</div>
                  </div>
                  <div class="event-time">
                    <div class="text-center">
                      <i class="fa fa-calendar"></i>&ensp;<?php echo $app->eventDate($event['event_date']) ?>&ensp;&ensp;
                      <i class="fa fa-clock-o"></i>&ensp;<strong><?php echo date('G:i', strtotime($event['event_date'])) ?></strong>
                    </div>
                  </div>
                  <h4 class="event-main-title"><a href="#">"<?php echo $event['event_title'] ?>"</a></h4>
                  <div class="event-description">                    
                    <p><?php echo $event['event_description'] ?></p>
                  </div>                               
                </div>
              </div> 
            <?php endforeach; ?>
            <?php else : ?>
              <div class="alert alert-danger" translate="TEXT_NO_DATA">Brak danych ...</div>
            <?php endif; ?>
          </div>

          <div class="see-all">
            <a href="javascript:void(0);"><i class="fa fa-trophy"></i>&ensp;<span translate="TEXT_SEE_ALL_EVENTS">Zobacz wszystkie</span></a>
          </div>
        </div>          
      </div>
    */
    ?>
    </div>  

  </div>
</section>
