<aside class="sidebar">
  <div class="row">

    <div class="col-md-12 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="head-border with-icon">
            <a href="https://www.youtube.com/channel/UCmoEcPbuk5tMwmq-KrfVsXg/feed" ><span class="header-icon" data-original-title="{{'TEXT_SEE_IN_YOUTUBE'| translate }}" data-tooltip data-placement="right"><i class="fa fa-youtube-square"></i></span></a>            
            <span translate='TEXT_VIDEO_OF_DAY'>Nasz kanał YouTube</span>            
          </h3>                    
        </div>
        <div class="panel-body panel-video">
          <div class="preloader"></div>
          <div class="row row-for-video"></div>
        </div>
      </div>
    </div>

    <?php
    //@todo lepsze ogarniecie metod
    $settingsPanel = new methods();
    $custom = $settingsPanel->getSettings();
    ?>

    <?php if ($custom['settings_visible'] == 'yes') : ?>
      <div class="col-md-12 col-sm-6">
        <div class="panel panel-default hidden fadeIn" id="panelSettingsPL" ng-class="{'hidden': class_status_pl }">
          <div class="panel-heading">
            <h3 class="head-border with-icon">
              <span class="header-icon"><i class="fa fa fa-futbol-o"></i></span><span><?php echo $custom['settings_title_pl'] ?></span>
            </h3>                    
          </div>
          <div class="panel-body">
            <div class="training-panel">
              <?php echo $custom['settings_content_pl'] ?>                
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-sm-6">
        <div class="panel panel-default hidden fadeIn" id="panelSettingsEN" ng-class="{'hidden': class_status_en}">
          <div class="panel-heading">
            <h3 class="head-border with-icon">
              <span class="header-icon"><i class="fa fa fa-futbol-o"></i></span><span><?php echo $custom['settings_title_en'] ?></span>
            </h3>                    
          </div>
          <div class="panel-body">
            <div class="training-panel">
              <?php echo $custom['settings_content_en'] ?>                
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>
    
    <?php $allEvents = $settingsPanel->getAllEvents(); ?>
    <div class="col-md-12 col-sm-6">
      <div class="panel panel-default fadeIn" id="bigcalendar">
        <div class="panel-heading">
          <h3 class="head-border with-icon">
            <span class="header-icon"><i class="fa fa-calendar"></i></span><span translate="TEXT_CALENDAR">Kalendarz</span>
          </h3>                    
        </div>
        <div class="panel-body events-panel">
            <?php if ($allEvents) : ?> 
              <?php foreach ($allEvents as $key => $event) : ?>
                <div class="row <?php echo $app->checkIfObsolete($event['event_date']) ?>">
                  <div class="col-lg-2 col-md-3 col-sm-2 col-xs-2 events-date" data-date="<?php echo $app->eventCounter($event['event_date']) ?>">
                    <span class="day"><?php echo date('d', strtotime($event['event_date'])) ?></span>
                    <p><span class="month"><?php echo date('m', strtotime($event['event_date'])) ?></span><span class="year">/<?php echo date('Y', strtotime($event['event_date'])) ?></span></p>
                  </div>
                  <div class="col-lg-10 col-md-9  col-sm-10 col-xs-10  events-name">
                    <p><?php echo $event['event_title'] ?></p>
                    <p><i class="fa fa-clock-o"></i>&ensp;<strong><?php echo date('G:i', strtotime($event['event_date'])) ?></strong></p>
                  </div>
                </div>
              <?php endforeach; ?>
            <?php else : ?>

            <?php endif; ?>
            </div>          
        </div>
      </div> 
    <?php require_once("lib/_partials/facebook.phtml"); ?>
    <div class="col-md-12 col-sm-6">		  
      <div class="panel panel-default fadeIn">
        <div class="panel-heading">
          <h3 class="head-border with-icon">
            <span class="header-icon"><i class="fa fa-facebook"></i></span><span>Facebook</span>
          </h3>                    
        </div>
        <div class="panel-body panel-facebook text-center">
          <div class="fb-page" data-href="https://www.facebook.com/polishfootballacademydragonsunited" 	
               data-small-header="false" 
               data-width="360"
               data-adapt-container-width="true"
               data-hide-cover="false" 	
               data-show-facepile="true" 
               data-show-posts="true">		  
            <div class="fb-xfbml-parse-ignore">	
              <blockquote cite="https://www.facebook.com/facebook">
                <a href="https://www.facebook.com/facebook"><div class="preloader"></div></a>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</aside>  

<?php /*
  <div class="sidebar">
  <div class="box">
  <h2 class="title">Reklamy</h2>
  <div class="adsense">
  <script type="text/javascript">
  google_ad_client = "ca-pub-2109333129587576";
  /* new.malytramwaj
  google_ad_slot = "1641383897";
  google_ad_width = 300;
  google_ad_height = 250;
  </script>
  <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
  </div>
  <p><small>Chcesz dodać reklamę? Zadzwoń do nas :)</small></p>
  <div class="clear"></div>
  </div>
  <div class="box">
  <!--<h2 class="title">Wyniki meczów</h2>
  <div class="scores">
  <div>
  <h3>Trampkarze</h3>
  <?php $scoreT = helpers::score('t') ?>

  <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
  <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
  <p class="tabela"><a href="<?php echo $app->basePath('table/trampkarze') ?>"><span>terminarz i wyniki</span></a></p>
  </div>
  <div>
  <h4>Młodzicy</h4>
  <?php $scoreT = helpers::score('m'); ?>

  <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
  <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
  <p class="tabela"><a href="<?php echo $app->basePath('table/mlodzicy') ?>"><span>terminarz i wyniki</span></a></p>
  </div>
  <div>
  <h3>Orliki</h3>
  <?php $scoreT = helpers::score('o'); ?>

  <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
  <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
  <p class="tabela"><a href="<?php echo $app->basePath('table/orliki') ?>"><span>terminarz i wyniki</span></a></p>
  </div>
  <div>
  <h4>Żaki</h4>
  <?php $scoreT = helpers::score('z'); ?>

  <p class="wyniki"><span <?php echo (intval($scoreT['score_team_win_goals']) > intval($scoreT['score_team_loss_goals']) ? 'class="winner"' : 'class="winner" style="font-weight:normal;"') ?> > <?php echo $scoreT['score_team_win'] ?></span> <span><?php echo $scoreT['score_team_win_goals'] ?></span> : <span><?php echo $scoreT['score_team_loss_goals'] ?></span> <span <?php echo (intval($scoreT['score_team_loss_goals']) > intval($scoreT['score_team_win_goals']) ? 'class="looser" style="font-weight:bold;"' : 'class="looser" ') ?>><?php echo $scoreT['score_team_loss'] ?></span></p>
  <p class="date"><span><?php echo $scoreT['score_time'] ?></span></p>
  <p class="tabela"><a href="<?php echo $app->basePath('table/zaki') ?>"><span>terminarz i wyniki</span></a></p>
  </div>
  </div>
  <div class="clear"></div> -->
  </div>
  </div>
 */ ?>