<div class="panel panel-default">
  <div class="panel-heading">                    		        	
    <h3 class="head-border"><?php echo htmlspecialchars($news['news_title']); ?></h3>
  </div>
  <div class="panel-body less-padding">     
    <div class="information last-info">
      <?php if ($news['news_image']) : ?>
        <div class="news-image">
          <a href="<?php echo $app->basePath('admin/img/news/' . $news['news_image']) ?>" data-lightbox="image-1" title="<?php echo htmlspecialchars($news['news_title']) ?>">
            <img src="<?php echo $app->basePath('admin/img/news/' . $news['news_image']) ?>" alt="" title="" class="img-responsive">
          </a>
        </div>
      <?php endif; ?>

      <?php if ($news['news_video']) : ?>
        <div class="news-video">
          <iframe frameborder="0" class="frame-video" height="360" src="<?php echo $news['news_video']; ?>?showinfo=0&amp;autohide=1&amp;rel=0"></iframe>
        </div>
      <?php endif; ?>

      <div class="news-tiny"><?php echo $news['news_desc'] ?></div>

      <?php if ($news['news_file'] != NULL) : ?>              
        <p class="extra_files" translate="TEXT_FILES">Pliki</p>
        <a class="extra-files-item" href="<?php echo $app->basePath('admin/files/' . $news['news_file']); ?>" title="{{'TEXT_FILES_CLICK_TO_DOWNLOAD' | translate }}">
          <span translate="TEXT_FILE_DOWNLOAD">Pobierz plik</span>
        </a>
      <?php endif; ?>            

      <div class="news-date"><?php echo date('d.m.Y G:i', ($news['news_update'])); ?></div>					
    </div>

    <div class="news-back">
      <a href="<?php echo $app->basePath($returnUrl); ?>" class="btn btn-default"><i class="fa fa-angle-double-left"></i>&ensp;<span translate="TEXT_BACK">Powrót do listy</span></a>
    </div>
  </div>

</div>