<?php
  $methods = new methods();
  $singleGallery = $methods->loadLastAddedGallery();
?>
<section class="small-offset">
  <div class="panel panel-default">
    <div class="panel-heading">				
      <h3 class="head-border" translate="TEXT_NEWEST_GALLERY">Ostatnia galeria</h3>				
    </div>
    <div class="panel-body less-padding">          

      <?php if ($singleGallery) : ?>
        <div class="information gallery-panel-body">
          <div class="row gallery-wrapper">
            <?php foreach ($singleGallery as $key=>$i) : ?>
              <div class="col-md-3 col-sm-4 col-xs-6">                
                <div class="img-information">
                  <img src="<?php echo $app->basePath('admin/img/gallery/small_' . $i['pic_name']) ?>" title="" alt="img" class="img-responsive"/>
                  <a class="overlay" href="<?php echo $app->basePath('admin/img/gallery/' . $i['pic_name']) ?>" data-lightbox="roadtrip">
                    <span class="circle"><i class="fa fa-search"></i></span>
                  </a>    
                </div>
              </div>
            <?php if ($key >= 10 ) : ?>
              <div class="col-md-3 col-sm-4 col-xs-6">
                <div class="arrow-right-big img-information">					
                  <div class="img-information">						
                    <img src="<?php echo $app->basePath('admin/img/gallery/small_' . $i['pic_name']) ?>" title="" alt="img" class="img-responsive"/>	
                    <a href="<?php echo $app->baseUrl('gallery/' . $i['pic_gallery_id']) ?>" class="overlay">						
                      <span class="circle" data-original-title="Więcej zdjęć w galerii" data-tooltip ><i class="fa fa-angle-double-right"></i></span>
                    </a>
                  </div>                  
                </div>
              </div>
              <?php break;  ?>
            <?php endif; ?>
            <?php endforeach; ?>
          </div>
        </div>
      <?php else: ?>
        <div class="alert alert-warning" translate="TEXT_NO_DATA">No data ...</div>
      <?php endif; ?>

      <div class="news-back">
        <a href="<?php echo $app->basePath('gallery') ?>" class="btn btn-default">
          <span translate="TEXT_GO_TO_GALLERY" class="ng-scope">Zobacz więcej</span>&ensp;<i class="fa fa-angle-double-right"></i>
        </a>                        
      </div>      
    </div>    
  </div>				
</section>