<header>
  <div class="headerbox">
    <div class="container">
      <div class="row">

        <div class="col-md-2 col-sm-2 logo">
          <a href="<?php echo $app->basePath('') ?>" title="Home">                            
            <img src="<?php echo $app->basePath('public/img/logo2.png') ?>" alt="Logo" class="logo_img">
          </a>
        
        </div>

        <div class="col-md-8 col-sm-8 adds">          
          <span class="club-motto" translate="APP_SLOGAN">Razem możemy więcej</span>          
        </div>
 
        <div class="col-md-2 col-sm-2 lang">
          <form class="form-inline pull-right">
            <div class="form-group">
              <button class="btn btn-lang-pl" ng-class="{'gray': class_status_pl }" data-ng-click="changeLanguage('pl')" data-lang="pl">&ensp;</button>              
            </div>
            <div class="form-group">
              <button class="btn btn-lang-uk" ng-class="{'gray': class_status_en }" data-ng-click="changeLanguage('en')" data-lang="en">&ensp;</button>
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div id="nav-sticky-wrapper" class="nav-sticky-wrapper">         
    <?php require_once("top_menu.phtml"); ?>    
  </div>
</header>

