<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
    <link href="public/css/bootstrap.min.css" rel="stylesheet" media="all">
    <link href="public/css/docs.css" rel="stylesheet" media="screen">
    <link href="public/js/jquery-ui/css/smoothness/jquery-ui.min.css" rel="stylesheet" media="screen">
    <link href="public/js/vendor/datetimepicker/dist/jquery-ui-timepicker-addon.css" rel="stylesheet" media="screen">
    <link href="public/css/bootstrap-fileupload.min.css" rel="stylesheet" media="screen">
    <link href="public/css/style.css?v=2015" rel="stylesheet" media="all">
    <link rel="shortcut icon" href="public/img/favicon.ico">
  </head>
  <body>