    <script src="js/jquery-1.9.1.min.js"></script>
	<script src="js/jquery-ui/js/jquery-ui-1.10.3.custom.js"></script>
    <script src="js/vendor/datetimepicker/dist/jquery-ui-timepicker-addon.min.js"></script> 
    <script src="js/bootstrap.min.js"></script>
    <script src="js/bootstrap-tooltip.js"></script>
    <script src="js/vendor/tinymce/js/tinymce/tinymce.min.js"></script>       
	<script src="js/bootstrap-fileupload.min.js"></script>
    <script src="js/app.js"></script>   
    
  </body>
</html>