<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/docs.css" rel="stylesheet" media="screen">
    <link href="js/jquery-ui/css/smoothness/jquery-ui.min.css" rel="stylesheet" media="screen">
    <link href="js/vendor/datetimepicker/dist/jquery-ui-timepicker-addon.css" rel="stylesheet" media="screen">
    <link href="css/bootstrap-fileupload.min.css" rel="stylesheet" media="screen">
    <link href="css/style.css?v=2015" rel="stylesheet">
  </head>
  <body>